### ISSUE TITLE
Migrate non AO assets to AO

### ISSUE THREAD

**Issue by NickJ202** [permaweb/bazar#105]
- We need a way to migrate old assets into AO
   - Create a button along side any asset in old bazar that you own with the label 'Migrate to AO'
   - Use the existing data and complete the AO asset creation process that is implemented here https://github.com/permaweb/helix/blob/main/src/views/Upload/index.tsx#L335

**Comment by VinceJuliano** [comment]
This needs to be added to the collections page to migrate whole collections.
