### ISSUE TITLE
U / PIXL / Streak migration

### ISSUE THREAD

**Issue by NickJ202** [permaweb/bazar#106]
PIXL Migration

- Fetch smartweave pixl state
- find profiles
- if no profile use wallet
- dry-run current ao-bazar PIXL process BALANCES
- append existing id balances (add them)
- replicate ao pixl for testing
- set balances in an eval
- examine results

Streak Migration

- Fetch smartweave streak state
- find profiles, if no profile use wallet
- dry-run current ao-bazar Streak state
- replicate ao streaks for testing
- If old streak is higher then new streak, replace it in the new bazar
- set state in eval
- examine results

U Migration

- Fetch smartweave U state
- use only wallets that are pixl holders
- for each wallet calculate U * (find conversion)
- set balances

**Comment by VinceJuliano** [comment]
With U everyone will receive wrapped AR relevant to their amount of U. This can be determined via permaswap/everpay network and seeing what the U token is worth.
